source "https://rubygems.org"
gem 'sinatra'
gem 'sinatra-portier'
gem 'sinatra-contrib'
gem 'puma'
gem 'open_uri_redirections'
gem 'feedparser'
gem 'sqlite3', '~> 1.6'
gem 'hashids', '~>1.0'
gem 'rack-rewrite'
gem 'nokogiri'
gem 'lru_redux'
gem 'moneta'
gem 'thread'
gem 'jsonpath'
gem 'to_regexp'
gem 'american_date'
gem 'twitter'
gem 'throttle-queue'
gem 'capybara'
gem 'selenium-webdriver'
gem 'oga'
gem 'strings'
gem 'httparty'
gem 'addressable'
gem 'rss'
gem 'test-unit'