source "https://rubygems.org"
gem 'sinatra'
gem 'sinatra-portier', '~>2.0'
gem 'sinatra-contrib'
gem 'puma'
gem 'rack'
gem 'open_uri_redirections'
gem 'feedparser'
gem 'sqlite3'
gem 'hashids', '~>1.0'
gem 'rack-rewrite'
gem 'nokogiri'
gem 'lru_redux'
gem 'jsonpath'
gem 'to_regexp'
gem 'american_date'
gem 'throttle-queue'
gem 'ferrum'
gem 'oga'
gem 'strings'
gem 'httparty'
gem 'addressable'
gem 'securerandom'
gem 'rss'
gem 'scylla'
gem 'dalli'
gem 'sanitize'
gem 'base64'
gem 'finishing_moves'
gem 'oxml', git: 'https://github.com/onli/oxml', branch: 'merged'
gem 'janeway-jsonpath', '~> 0.6.0'

gem 'test-unit'
gem 'rake'
